### ISSUE TITLE
PowerDown Pin Conflicts with EMMC DAT0 Line

### ISSUE THREAD

**Issue by dashneptune** [jacobhuesman/bbb_localization_cape#2]
This shouldn't be an issue for now, but we need to change the power down pin from being on P8.25 to being on P28.6 on the beaglebone side. We aren't using EMMC but we should probably change it to be compatible with Linux driver  in the future. Also, the DAT0 pin is the one that is used at startup for the thing, and its bidirectional, so we may cause issues with the output driver...

**Comment by jacobhuesman** [comment]
Fixed
