### ISSUE TITLE
XTAL for XCLK

### ISSUE THREAD

**Issue by dashneptune** [jacobhuesman/bbb_localization_cape#5]
It may be prudent in a future revision to move to a crystal for for the clock on the ov7670/MT9V111. All of the cameras I've seen support a 24MHz crystal, which would have lower jitter. Also, it looks like the max I can do with the BBB is a 12 MHz without busting out one of the system clocks, which I'm looking at doing. We can probably use the system clock, I'll update this on my progress

**Comment by dashneptune** [comment]
It looks like p9.25 can be used as a rough 24 Mhz clock...as long as gpio 1_27 is used as an output and brought high

**Comment by dashneptune** [comment]
I'll try to pototype that this week

**Comment by dashneptune** [comment]
Prototype is proven...We can use P9.25 for XCLK without utilizing any extra components

**Comment by jacobhuesman** [comment]
Still need to implement on cape

**Comment by jacobhuesman** [comment]
Done
